groups:
  - name: node_down
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 5s
        labels:
          user: test
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5s."
