version: "3"

networks:
  monitor:
    driver: bridge

services:
  lookoutserver:
    build: .
    container_name: lookoutserver
    restart: always
    volumes:
      - $PWD/foo.properties:/tmp/foo.properties
    ports:
      - "9090:9090"
    links:
      - es
    networks:
      - monitor
    environment:
      - JAVA_OPTS="-Dlookoutall.config-file=/tmp/foo.properties"
  # web可视化数据
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - monitor

  es:
    image: elasticsearch
    container_name: es
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
